language: node_js
node_js:
- '0.10'
env:
  global:
  - PRODUCTION_BRANCH=master
  - GH_REF=github.com/wbg-bigdata/nightlights-api.git
  - PGSSLMODE=require
  - secure: rP/40+OMaGb9oCj0bsZ0fMDGvsRrcWN2BI57ocd3/Ib8acO3HtJgsU8L+4yiKKZY8NN3ZyREJrZ+0EXDLoNZ4OZEvIFtE/UfwaGCsoUA1nmK5igTwBRH1FlCWqNcnC/9GINrwHVrEoFOKkjix2/fnJjHzX6s+n7OTOTEuTXOdjH0MIfNQKPnKR+5+urjZbZEGwYAh6BumEOAEUQqklUEsY7n/MuEBhoTUi/6QHAzbw+QvrDzpVEktkoDSQlyWDDi+uNzPU1/9rRXyfw6ih2vkNjwBwfcBRNKJDNc1iVVzbw3+kxKrpvUEXd7wsW3B+t29ZmNq74V++IyiF/lgZXvGWsgCH/uGzR5UW9Btp6ppcOe98lRAwwTihReG+QhN1qVkqETI9ZE+dvN5atSZ8BJrv1jXY6QXCJ20/KdVMjs3lMGlJdgh/iLdMAsGU7f+efwn1KqMZuQ5Lc+lnIgH2wvI9WbAmS+Jy2b0O2xT9wH1g2f8SyOziGn6+dkejrbQBKa831DZI8ED+FTqNO97k4V/8Nt3JlE8shwC4hY/dbyruavzAuSk9U3HYEmHLXrQcx0ZztVmoZPMMyAxC2JlqOnII6jD4fv4meF/nijkFtD/CI/7qJDwHWTRhDM3+rqe25c/CuL32ogpmi01RS5AMtiA5DYPswYHUsmeuEQFSv/7C0=
before_install:
- chmod +x ./.build_scripts/doc_deploy.sh
script: npm test
after_success:
- "./.build_scripts/doc_deploy.sh"
deploy:
  provider: heroku
  app: nightlights-api
  on:
    repo: wbg-bigdata/nightlights-api
    branch: master
  api_key:
    secure: BA2CtYbzKthVdLUU3w3XYDkNaaZ36xubrHi0igq5KwNEz5mQoT8DU/MXHzp5YFX4IiDNnG9qRmpY0TtfSk51RDEdRXT3gDdfSOI8h4IPhnhTjNA+sfcPHBiKlmzpTlAUzOVIu3X5VEYhnizJKpVyuovxAm602lj245mM4FrQFe5l+ZJx4xl8f7+48MuzWGsc5dMI+gz8rASlmlTNf1+Dy92qLePwaPnntOayVWxcA7VJ0OFmTkV2LNpGOr1jFaoSl3bdVZXMzyynbpHrPRwyI/B0jUE6urAsOeQegmdYFuGYOCxOZSS9zjdfASsxDj2IGy4sivgdjIDWKhMveFHceIfwuwOPxJJkR0oil6w3zAJ0qqitV3BaaEQOrVDEKVrWALdmqXoGWzgPDqN1Y2mmZ0c3l2yRF5sf999/X2bn6GUQF67b5O3ysMOBTQ7qBiKBB0vYVs8CkixE8H17vpni2sq6Z3nsEHPG7aIMcx+zsdJF2GxMLeFsRs8dhUHSRrdvmXpsDL7wVCoYJ0VjbAFWmr2RDE5jMms6VCsYHuiIYKyIczZ4aUVMuBogiKY1JYNxAIMsaB2623HN8jZYCbJ6kD14dVQWx4FBspyw3kLtTGtzZmI45d8fUVR/Q/00oWNpZICe7+9CUCCcCrMzyDbIwTMuX0Jwkpp4uNdlh1aP7Oo=
