language: node_js
node_js:
- '0.10'
env:
  global:
  - PRODUCTION_BRANCH=master
  - GH_REF=github.com/developmentseed/india-lights-api.git
  - PGSSLMODE=require
  - secure: Lciz517uFBqErd+fLO30hYoWJ9dN56Kp4oBDjILWhz/+RRFeOjRXihE3+XMR02fmxm6B8TEGYYIZy8bvnw/jP9jXT0PYei1908qxexewLHhgNUIWTOhLybPNcRoZxPaRbjOG+N8sSzQLRTZhYGDCUIu5OSOFHVodndfDV01ONvdiOD4fwGYYTiuCOAVmgjaUzNhrWCfD2ASJ7mM8vXMMkm2awhoCQ0m8iu1+55UtqxaZphLljIK3JujycIO418fQrnO3IGHjYPFqJpb9BxJ6eH80Uk3oGt7BH/7JjLqe/eD/EbY3LmYatPE1jy63VfwoDuxvFhRzhAg4P3wH01Urlx05+DXfDhOqtC6t+uINmaopqf2BB1vFuJzezuTFICJUlj8JPDfKB+4GJBkHZFu6CpZZpdc//5NJQdlEf6+3uO0v/piVXnQI3DFsvHXpe0I1MJdihPbOy4rnlPd+ufhViH+dUSvj3S2uuiOi4Q3Z+gF1yJTIMFUHlxv5BCqrGmTudJhaTcv+BSWYQSlWJqm3KhNjCCxfLlF9Cd0mh0deo/b+xV358SDnwpiLawuLyaMnwdyZeNl/lnTFGRjW5NDGzmx6nCGszQYgffZ80lJwvMKT+QwYlDD2wHzRwBSRCRF/MCH/jQEdp3VwYYar6Kx8gcaDR5R357BuZTsAp9HIlYQ=
before_install:
- chmod +x ./.build_scripts/doc_deploy.sh
script: npm test
after_success:
- "./.build_scripts/doc_deploy.sh"
deploy:
  provider: heroku
  api_key:
    secure: 2kIkx7FuwooMiorCvbGkFrUP5rrX/oWR5vWAS3+snw2Do6pH9hiR8JdRqWoGvtFt5itU9odfBa2l5G8qDRHj4QfJ3H4vudxvsfb4HMpcjCdkq5X0jglpWe3+iI3ecziOWbWoBqSN9eXVFxNGW5ikwqf6LqZ0sbUhAaFDdRjYEeL+1V/DzlmujjDHHVFwzaunrfo3SVgPak0YMGqYt8g9BGn7/GXx6VArA0m6okMlBrktnBr9mD9fI63GqK6jCNDz37f9JpQliA7PeNPGxgyBDe+q79PgAOoSNgf9B65N11vPh+aIsG+yZPvk7IocIEdZyCGrjaibYB7+tVQdakSgWnZfGg1BFdoqqFaD6es1jBn7Rd9i7ob20FyHUKVD6gfKsQOFtf4jiAQsXJAaFxlnhooJlTHn3KPZklzMD0sWkBGJBizlVepDTIjd2BcEH/LcF+92FeRHfoqnmA4ucTPsP5wOUtKo2jkaD8pWf7/4PPRJdnNcWSHE5JTv6n4H5TJjpZxqy3i4NQUKPKdVF7pHA5yoW5WBYLGtg/hwkVfO6Ydbb/Q7KHH7oSIuJGGZhLFwLbPuKm8gl+F441RLoiH08p2XNzp/pjY6t7fvE4xtPzYScE8EmHYKXxymiBIygzNhkqBUgnjsqi6kY25b7nOVvKob/1ONt4r7G190UzBf3Jg=
  app: india-lights
  on:
    repo: developmentseed/nightlights-api
    branch: develop
