language: node_js
node_js:
- '0.10'
env:
  global:
  - PRODUCTION_BRANCH=master
  - GH_REF=github.com/wbg-bigdata/nightlights-api.git
  - PGSSLMODE=require
  - secure: rP/40+OMaGb9oCj0bsZ0fMDGvsRrcWN2BI57ocd3/Ib8acO3HtJgsU8L+4yiKKZY8NN3ZyREJrZ+0EXDLoNZ4OZEvIFtE/UfwaGCsoUA1nmK5igTwBRH1FlCWqNcnC/9GINrwHVrEoFOKkjix2/fnJjHzX6s+n7OTOTEuTXOdjH0MIfNQKPnKR+5+urjZbZEGwYAh6BumEOAEUQqklUEsY7n/MuEBhoTUi/6QHAzbw+QvrDzpVEktkoDSQlyWDDi+uNzPU1/9rRXyfw6ih2vkNjwBwfcBRNKJDNc1iVVzbw3+kxKrpvUEXd7wsW3B+t29ZmNq74V++IyiF/lgZXvGWsgCH/uGzR5UW9Btp6ppcOe98lRAwwTihReG+QhN1qVkqETI9ZE+dvN5atSZ8BJrv1jXY6QXCJ20/KdVMjs3lMGlJdgh/iLdMAsGU7f+efwn1KqMZuQ5Lc+lnIgH2wvI9WbAmS+Jy2b0O2xT9wH1g2f8SyOziGn6+dkejrbQBKa831DZI8ED+FTqNO97k4V/8Nt3JlE8shwC4hY/dbyruavzAuSk9U3HYEmHLXrQcx0ZztVmoZPMMyAxC2JlqOnII6jD4fv4meF/nijkFtD/CI/7qJDwHWTRhDM3+rqe25c/CuL32ogpmi01RS5AMtiA5DYPswYHUsmeuEQFSv/7C0=
  - secure: PZc+cYUlbDV62m3w3oCfKaZqt975wYC0p4EdHlOwLS5Bpv8e5hFZX7l2OgIDaigFE7EoFpVZI/GhA3fNA0ooUBVRvliUXmY8jD9juoXQXsh+3ahhClKl85fnn92QAc/hfK9A+jiqxgGIcNUPY4VKT1P4G+TwXT7ffB+dGwtJwYD3EAmuM/FpPVbdtv2ktqGLObctHyagDaM8j1C0pkIi0lUvAp4Ey/8jUuooiJ1CE6+YZvSp9Zecx3vY5szcvNso0ntYVlaQC4f1PI4c46RBSiqh9WScA2CPqUQ2agdOt+3GSCWDb7Gw85VJ8YvJRsRxq3ZpjDs5yvbSgRWuxqkM6dqGjph0sXvQydQ8IVBPpMxjGMZyTPYJh8+J8WRmsq4UcztgsOQosABxMbvfKHArTMINRkNLGxcYMBO1BenfmWy048Z/vjystYj8mAwFEyPjghoh/Ol0rQ17pTF8pDTTJyvtEQQT3Uzjif14K1Dr3meBYmwHXW8zd5PEH67lIpPIIp181vljbTFPxamMceOnpNE70CJ8AZ+2dtLEkKLBLziJodjOPGp9GrViOM6FBG/+BVAM7KmnvxmI3Xcv7SCJKFMYwNo8PfpeipEXnKZ9m4OOyTKDSa0Xv4ZSPtkg4GRAH8Imqg0aBdsRTN6fW2w0O/nQcoL0ElHrBh+a8SUjn04=
before_install:
- chmod +x ./.build_scripts/doc_deploy.sh
script: npm test
after_success:
- "./.build_scripts/doc_deploy.sh"
deploy:
  provider: heroku
  app: nightlights-api
  on:
    repo: wbg-bigdata/nightlights-api
    branch: master
  api_key:
    secure: DAsSabd76CtKMKRGkRGNKXzHe5gDQdJUjEQ7snBlyAqXW/50PwzAnD4rRDJLNpzyMIRnhSMRGY9zrAbH9M7+PVh4lTPALVPsQQuIkZI+cqJO/VG20zjm3XeH3aybZxv6oHDq2vLEARG7uMN+5y1M7YiQMKG+P54E/N/4/xxmundnThepBycb9KXkjqc2FFEsL49jTeO4QE0DXFuESNHmCahdJuU1UpLxfa+Vym8Ijclhl7eoSHXf7+OmxUtsEMfDVaLSdVt5yPhYQ8dRvDf5ksxYqR+EWflimiUofi/lVcahEaq0KDH6o7W3ZZQ1H671N9CNfTHEA/d0g912HP7KjxKUdYdkW4AjdMIp2mG0zFD5+2NKqWf4f3iqqeB0M1715D1F25HzIOoWh78kBSfuxy5Yja84NUFyX+brw8guyGpN2hoOdR1kuQrBVkZtTymJlQ6Ao9VKrkQQSsFo26RPnT26VOB015aDYC+EuuLyZYBrJaw9JwVuZzRmzHfbr3XBmw5HpDNuLpGfZ8GFIos9OLJg8SRRFuLS2NJa7iCTbLfsG8qRdsuEHUmcb4GNe3e8H/go3BSXWD8l6D8GMpTA/av5rZXqF7Y9v6K8hxMI4PbMSGpf5VbRPoFNDAhdimebSPE1rMGJLxWbL4kD8LduN0Kh3DFilv/vLxaQYwcQOQ8=
